Repository ProjectNeura/MIPCandy, pull requests merged in 2025-09, with the labels that each got.

#22 Support loading default values of arguments of `Trainer.train()` from settings
  mipcandy/presets/segmentation.py
  mipcandy/settings.yml
  mipcandy/training.py
Labels: enhancement, todo

#29 Multi-channel 3D visualization crashes in `SegmentationTrainer._save_preview()`
  mipcandy/data/visualization.py
  mipcandy/presets/segmentation.py
Labels: bug, todo

#31 `SegmentationTrainer` crashes because `"min_all" not implemented for 'UInt16'` during preview generation
  mipcandy/presets/segmentation.py
Labels: bug, todo

#35 Fix `SlidingWindow` 3D metadata dimensions causing revert failure
  mipcandy/sliding_window.py
Labels: bug, todo

#46 Set the model to inference mode during sanity check
  mipcandy/sanity_check.py
Labels: bug, enhancement, todo
